### ISSUE TITLE
A bug on using protein family

### ISSUE THREAD

**Issue by chao1224** [tencent-ailab/DrugOOD#10]
Hi,

I'm testing the dataset curated from protein family, e.g., `configs/curators/sbap_core_ki_protein_family.py`. And I get the following exception:
```
Traceback (most recent call last):
  File "xxx/drugood/apis/curate.py", line 14, in curate_data
    data = curator.data_splitting(data)
  File "xxx/drugood/curators/curator.py", line 206, in data_splitting
    domain_value = domain_func(value_for_generating_domain)
  File "xxx/drugood/curators/get_domain_info.py", line 75, in protein_family
    class_id = self.protein_family_getter(protein_seq)
  File "xxx/drugood/curators/chembl/protein_family.py", line 48, in __call__
    target_level_class_id = self.get_target_level_class_id(class_id)
  File "xxx/drugood/curators/chembl/protein_family.py", line 37, in get_target_level_class_id
    class_id_cur_level = self.dict_id_to_parent_level[class_id_cur_level][0]
KeyError: None
```
It turns out that `protein_family_level` is None.

--------

A quick update: this [line](https://github.com/tencent-ailab/DrugOOD/blob/main/drugood/curators/get_domain_info.py#L16) fails to pass in the `protein_family_level`.

**Comment by Tigerrr07** [comment]
I also have the same question, so I debug for that, the problem comes from the following code lines:
https://github.com/tencent-ailab/DrugOOD/blob/61a70e4ad1fb227e4a264ed5ba87d4c78fdb4ae7/drugood/curators/curator.py#L198-L200
It should be modified to this:
``` python
domain_cfg = self.cfg.domain

domain_info_funcs_set = DomainInfo(domain_cfg, self.sql)
```
This is because `DomainInfo` needs to accept domain_cfg instead of the original cfg. By doing that, I can generate the dataset curated from protein family successfully.
